const transformIgnores = [
  ".*bail",
  ".*ccount",
  ".*character",
  ".*comma",
  ".*emoticon",
  ".*escape",
  ".*hast",
  ".*is-*",
  ".*github",
  ".*fault",
  ".*html",
  ".*longest-streak",
  ".*lowlight",
  ".*markdown",
  ".*mdast",
  ".*micromark",
  ".*parse",
  ".*property",
  ".*remark-directive",
  ".*remark-gfm",
  ".*rehype-*",
  ".*space",
  ".*stringify",
  ".*trim-lines",
  ".*trough",
  ".*unified",
  ".*unist",
  ".*vfile",
  ".*zwitch",
].join("|");
const config = {
  testEnvironment: "jsdom",
  testMatch: ["**/*.test.ts"],
  transformIgnorePatterns: [`/node_modules/(?!${transformIgnores})`],
};

module.exports = config;
